#!/usr/bin/env ruby


input = File
  .read(ARGV[0] || "input")
  .lines
  .map { |l| l.chomp.split("").map(&:to_i) }

counts = []
input.each do |line|
  line.each_with_index do |i, idx|
    counts[idx] ||= [0, 0]
    counts[idx][i] += 1
  end
end

gamma = counts.map { |pair| pair.find_index(pair.max).to_s }.join.to_i(2)
epsilon = counts.map { |pair| pair.find_index(pair.min).to_s }.join.to_i(2)

puts gamma * epsilon
