#!/usr/bin/env ruby

levels = ARGF
  .each_line
  .map { |line| line.split.map(&:to_i) }

def safe?(levels)
  safe_direction = levels.each_cons(2).all? { |(a, b)| a > b } || levels.each_cons(2).all? { |(a, b)| a < b }
  safe_delta     = levels.each_cons(2).all? { |(a, b)| (1..3).include? (a - b).abs }

  safe_direction && safe_delta
end

safe_levels = levels.select do |line|
  safe?(line) || line.each_index.any? { |i| new_line = line.dup; new_line.delete_at(i); safe?(new_line) }
end

puts safe_levels.length
