#!/usr/bin/env ruby

levels = ARGF
  .each_line
  .map { |line| line.split.map(&:to_i) }

puts levels
  .select { |line| line.each_cons(2).all? { |(a, b)| a > b } || line.each_cons(2).all? { |(a, b)| a < b } }
  .select { |line| line.each_cons(2).all? { |(a, b)| (1..3).include? (a - b).abs } }
  .length
