#!/usr/bin/env ruby

input = File.read(ARGV[0] || "input").split("\n")
horizontal = 0
depth = 0

input.each do |line|
  direction, amount = line.split(" ")
  if direction == "forward"
    horizontal += amount.to_i
  elsif direction == "down"
    depth += amount.to_i
  elsif direction == "up"
    depth -= amount.to_i
  end
end

puts horizontal * depth
